/** @type {import('cz-git').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 72],
    'subject-full-stop': [2, 'never', '.'],
    'subject-min-length': [2, 'always', 10],
    'body-max-line-length': [2, 'always', 100],
    'subject-case': [2, 'always', 'sentence-case'],
    'scope-enum': [2, 'always', [
      'tests',
      'deps',
      'config',
      'editor',
    ]],
    'type-enum': [2, 'always', [
      'feat',
      'fix',
      'docs',
      'style',
      'refactor',
      'perf',
      'test',
      'build',
      'ci',
      'chore',
      'revert',
    ]],
  },
  prompt: {
    defaultBody: '',
    useEmoji: false,
    defaultIssues: '',
    skipQuestions: [],
    defaultSubject: '',
    breaklineChar: '|',
    breaklineNumber: 100,
    confirmColorize: true,
    allowEmptyScopes: true,
    defaultScope: 'config',
    upperCaseSubject: true,
    allowCustomScopes: true,
    emptyScopesAlias: 'empty',
    allowEmptyIssuePrefix: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    allowCustomIssuePrefix: true,
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    markBreakingChangeMode: false,
    customIssuePrefixAlias: 'custom',
    allowBreakingChanges: ['feat', 'fix'],
    scopes: [
      { name: 'testing', value: 'testing' },
      { name: 'deps', value: 'deps' },
      { name: 'config', value: 'config' },
    ],
    issuePrefixes: [
      { value: 'closed', name: 'closed:   Issue has been processed' },
      { value: 'closes', name: 'closes:   Close this issue' },
      { value: 'fixes', name: 'fixes:    Fix the issue' },
      { value: 'resolves', name: 'resolves: Resolve the issue' },
    ],
    messages: {
      customFooterPrefix: 'Input ISSUES prefix:',
      customScope: 'Denote the SCOPE of this change:',
      generatingByAI: 'Generating AI commit subject...',
      generatedSelectByAI: 'Select AI-generated subject:',
      scope: 'Denote the SCOPE of this change (optional):',
      type: 'Select the type of change you\'re committing:',
      footer: 'List any ISSUES by this change. E.g.: #31, #34:\n',
      confirmCommit: 'Are you sure you want to proceed with this commit?',
      subject: 'Write a SHORT, IMPERATIVE tense description of the change:\n',
      breaking: 'List any BREAKING CHANGES (optional). Use "|" to break new line:\n',
      footerPrefixSelect: 'Select the ISSUES type of changeList by this change (optional):',
      body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
    },
    types: [
      { value: 'feat', emoji: ':sparkles:', name: 'feat:     A new feature' },
      { value: 'fix', emoji: ':bug:', name: 'fix:      A bug fix' },
      { value: 'docs', emoji: ':memo:', name: 'docs:     Documentation only changes' },
      { value: 'style', emoji: ':lipstick:', name: 'style:    Changes that do not affect the meaning of the code' },
      { value: 'refactor', emoji: ':recycle:', name: 'refactor: A code change that neither fixes a bug nor adds a feature' },
      { value: 'perf', emoji: ':zap:', name: 'perf:     A code change that improves performance' },
      { value: 'test', emoji: ':white_check_mark:', name: 'test:     Adding missing tests or correcting existing tests' },
      { value: 'build', emoji: ':package:', name: 'build:    Changes that affect the build system or external dependencies' },
      { value: 'ci', emoji: ':ferris_wheel:', name: 'ci:       Changes to CI/CD configuration or automation tools' },
      { value: 'chore', emoji: ':hammer:', name: 'chore:    Other changes that don\'t modify src or test files' },
      { value: 'revert', emoji: ':rewind:', name: 'revert:   Reverts a previous commit' },
    ],
  },
};
